export  const HEADERCONSTANTS= {
    homePage:{
        title:"Home",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    aboutPage:{
        title:"About us",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    aboutDetailPage:{
        title:"About us"
    },
    bankPage:{
        title:  "Banking",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    bankDetailsPage:{
        title:"Bank Details",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    bankingPage:{
        title:"Banking",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    cartPage:{
        title:"Cart",
        showCart:false,
        showWishList:true,
        showMenu:true
    },
    changePasswrdPage:{
        title:"Change Password",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    checkoutPage:{
        title:"Checkout",
        showCart:false,
        showWishList:false,
        showMenu:true
    },
    contactPage:{
        title:"Contact us",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    dealPage:{
        title:"Deals",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    downloadPage:{
        title:"Download",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
   eventPage:{
        title:"Events",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    forgetPasswordPage:{
        title:"Forgot Password",
        showCart:false,
        showWishList:false,
        showMenu:true
    },
    giftBoxPage:{
        title:"Gift Box",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    legalPage:{
        title:"Legal",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    loginPage:{
        title:"Login",
        showCart:false,
        showWishList:false,
        showMenu:true
    },
    loginDetailPage:{
        title:"Login Details",
        showCart:false,
        showWishList:false,
        showMenu:true
    },
    memberPage:{
        title:"Current Membership",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    myAccountPage:{
        title:"My Account",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    myOrderPage:{
        title:"My Orders",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    MyOrdersViewPage:{
        title:"View Orders",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    myTeamPage:{
        title:"My Team",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    notificationPage:{
        title:"Notification",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    passbookPage:{
        title:"Passbook",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    personalPage:{
        title:"Personal Profile",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    pointsAndCommisionPage:{
        title:"Points & Commission",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    productSoldReport:{
        title:"Product Sold Report",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    productAndService:{
        title:"Products & Services",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    registerEvent:{
        title:"Register Events",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    registration:{
        title:"Join Us",
        showCart:false,
        showWishList:false,
        showMenu:false
    },
    requestFund:{
        title:"Request Fund",
        showCart:false,
        showWishList:false,
        showMenu:true
    },
    searchPage:{
        title:"Search",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    settingPage:{
        title:"Setting",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    subscriptionPage:{
        title:"Subscription Plans",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    teamandMemberPage:{
        title:"Team and Members",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    updatePanPage:{
        title:"Update Pan",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    whishlistPage:{
        title:"Wishlist",
        showCart:true,
        showWishList:false,
        showMenu:true
    },
    productPage:{
        title:"",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    productDescription:{
        title:"",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    hierarchyPage:{
        title:"Hierarchy",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    VendorsListPage:{
        title:"Vendors",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    VendorsDetailPage:{
        title:"Vendor Details",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    DownloadViewPage:{
        title:"Downloads",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    ShippingAddressPage:{
        title:"Shipping Address",
        showCart:false,
        showWishList:false,
        showMenu:true
    },
    PersonalProfileEditPage:{
        title:" Edit Personal Profile",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    aboutUsDetailPage:{
        title:"",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    legalDetailPage:{
        title:"",
        showCart:true,
        showWishList:true,
        showMenu:true
    },
    WelcomePage:{
        title:"",
        showCart:false,
        showWishList:false,
        showMenu:false
    }
};
